version: "3.9"

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=employee.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A employee worker --loglevel=info
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=employee.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/code

  celery-beat:
    build:
      context: .
    command: celery -A employee beat --loglevel=info
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=employee.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/code

volumes:
  postgres_data:
