# Generated by Django 4.2.7 on 2024-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_admin_customuser_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annual_leave_days',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Personel'), ('admin', 'Yetkili')], default='staff', max_length=10),
        ),
    ]
