# Generated by Django 4.2.7 on 2024-11-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_work_hours',
        ),
    ]
