# Generated by Django 4.2.7 on 2024-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
        ('users', '0005_rename_is_admin_customuser_is_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='remaining_leave_days',
        ),
        migrations.AddField(
            model_name='customuser',
            name='worklog',
            field=models.ManyToManyField(blank=True, related_name='WorkLog', to='worklog.worklog'),
        ),
    ]
