# Generated by Django 4.2.7 on 2024-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0002_remove_leaverequest_reviewed_by_and_more'),
        ('worklog', '0001_initial'),
        ('users', '0006_remove_customuser_remaining_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leaverequest',
            field=models.ManyToManyField(blank=True, to='leaverequest.leaverequest', verbose_name='Leave Request'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='worklog',
            field=models.ManyToManyField(blank=True, to='worklog.worklog', verbose_name='WorkLog'),
        ),
    ]
