# Generated by Django 4.2.7 on 2024-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0002_remove_leaverequest_reviewed_by_and_more'),
        ('users', '0008_customuser_remaining_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='leaverequest',
            field=models.ManyToManyField(blank=True, related_name='leaverequest', to='leaverequest.leaverequest', verbose_name='Leave Request'),
        ),
    ]
